export enum params {
  badges = 'b',
  badgeInfo = 'bi',
  color = 'c',
  count = 'co',
  displayName = 'dn',
  duration = 'd',
  emotes = 'e',
  joined = 'j',
  login = 'l',
  message = 'm',
  messageId = '_id',
  messageType = 'mt',
  months = 'mo',
  parted = 'p',
  streak = 's',
  subInfo = 'si',
  systemMsg = 'sm',
  tier = 't',
  userId = 'uid',
}
